/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class Menu extends javax.swing.JFrame {
    int bagQty, shoesQty, trousersQty, shirtQty;
    double netTotal = 0.0;
    DecimalFormat df = new DecimalFormat("MYR0.00");

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bagButton = new javax.swing.JRadioButton();
        shirtButton = new javax.swing.JRadioButton();
        trousersButton = new javax.swing.JRadioButton();
        shoesButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        buyButton = new javax.swing.JToggleButton();
        bagQtyInCart = new javax.swing.JTextField();
        shirtQtyInCart = new javax.swing.JTextField();
        trousersQtyInCart = new javax.swing.JTextField();
        shoesQtyInCart = new javax.swing.JTextField();
        bagStock = new javax.swing.JTextField();
        shirtStock = new javax.swing.JTextField();
        trousersStock = new javax.swing.JTextField();
        shoesStock = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bagPrice = new javax.swing.JTextField();
        shirtPrice = new javax.swing.JTextField();
        trousersPrice = new javax.swing.JTextField();
        NETTOTAL = new javax.swing.JTextField();
        shoesPrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Stencil Std", 1, 18)); // NOI18N
        jLabel1.setText("WELCOME TO CUSTOMER CART");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );

        jLabel2.setFont(new java.awt.Font("Mistral", 1, 24)); // NOI18N
        jLabel2.setText("MENU");

        bagButton.setText("Bags");
        bagButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagButtonActionPerformed(evt);
            }
        });

        shirtButton.setText("Shirt");
        shirtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shirtButtonActionPerformed(evt);
            }
        });

        trousersButton.setText("Trousers");
        trousersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trousersButtonActionPerformed(evt);
            }
        });

        shoesButton.setText("Shoes");
        shoesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shoesButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabel3.setText("Products");

        jLabel5.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabel5.setText("Quantity in Cart:");

        jLabel6.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabel6.setText("Stock remaining:");

        jLabel7.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabel7.setText("Net Total:");

        buyButton.setText("BUY!");
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        jLabel8.setText("Price:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(trousersButton)
                            .addComponent(shirtButton, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shoesButton, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bagButton, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bagQtyInCart, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shirtQtyInCart, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trousersQtyInCart, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shoesQtyInCart, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(shoesStock, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(shoesPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bagStock, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(shirtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(trousersStock, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(trousersPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(shirtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bagPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NETTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bagButton)
                    .addComponent(bagQtyInCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bagStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bagPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NETTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shirtButton)
                    .addComponent(shirtQtyInCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shirtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shirtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trousersButton)
                    .addComponent(trousersQtyInCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trousersStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trousersPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shoesButton)
                            .addComponent(shoesQtyInCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shoesStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(shoesPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bagButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagButtonActionPerformed
        // TODO add your handling code here:
        Products product = new Bags();
        if (bagButton.isSelected()){
            bagStock.setText(String.valueOf(product.stock));
            bagPrice.setText(String.valueOf(product.price));
            
            bagQty = product.getQuantity();
            
            while(bagQty>product.stock){
                bagQty = Integer.parseInt(JOptionPane.showInputDialog("Over stock limit. Enter new amount: "));
            }
            
            bagStock.setText(String.valueOf(product.stockRemain(bagQty)));
            
            netTotal+=product.calcPrice(bagQty);
            
            NETTOTAL.setText(String.valueOf(df.format(netTotal)));
            bagQtyInCart.setText(String.valueOf(bagQty));
        }
        
        if (!bagButton.isSelected()){
            bagStock.setText(String.valueOf(product.stock));
            bagPrice.setText(String.valueOf(product.price));
            bagQtyInCart.setText("0");
            
            revertPrice(product.calcPrice(bagQty));
        }
    }//GEN-LAST:event_bagButtonActionPerformed

    private void shirtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shirtButtonActionPerformed
        // TODO add your handling code here:
        Products product = new Shirt();
        if (shirtButton.isSelected()){
            shirtStock.setText(String.valueOf(product.stock));
            shirtPrice.setText(String.valueOf(product.price));
            
            shirtQty = product.getQuantity();
            
            while(shirtQty>product.stock){
                shirtQty = Integer.parseInt(JOptionPane.showInputDialog("Over stock limit. Enter new amount: "));
            }
            
            shirtStock.setText(String.valueOf(product.stockRemain(shirtQty)));
            
            netTotal+=product.calcPrice(shirtQty);
            
            NETTOTAL.setText(String.valueOf(df.format(netTotal)));
            shirtQtyInCart.setText(String.valueOf(shirtQty));
        }
        
        if (!shirtButton.isSelected()){
            shirtStock.setText(String.valueOf(product.stock));
            shirtPrice.setText(String.valueOf(product.price));
            shirtQtyInCart.setText("0");
            
            revertPrice(product.calcPrice(shirtQty));
        }
    }//GEN-LAST:event_shirtButtonActionPerformed

    private void trousersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trousersButtonActionPerformed
        // TODO add your handling code here:
        Products product = new Trousers();
        if (trousersButton.isSelected()){
            trousersStock.setText(String.valueOf(product.stock));
            trousersPrice.setText(String.valueOf(product.price));
            
            trousersQty = product.getQuantity();
            
            while(trousersQty>product.stock){
                trousersQty = Integer.parseInt(JOptionPane.showInputDialog("Over stock limit. Enter new amount: "));
            }
            
            trousersStock.setText(String.valueOf(product.stockRemain(trousersQty)));
            
            netTotal+=product.calcPrice(trousersQty);
            
            NETTOTAL.setText(String.valueOf(df.format(netTotal)));
            trousersQtyInCart.setText(String.valueOf(trousersQty));
        }
        
        if (!trousersButton.isSelected()){
            trousersStock.setText(String.valueOf(product.stock));
            trousersPrice.setText(String.valueOf(product.price));
            trousersQtyInCart.setText("0");
            
            revertPrice(product.calcPrice(trousersQty));
        }
    }//GEN-LAST:event_trousersButtonActionPerformed

    private void shoesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shoesButtonActionPerformed
        // TODO add your handling code here:
        Products product = new Shoes();
        if (shoesButton.isSelected()){
            shoesStock.setText(String.valueOf(product.stock));
            shoesPrice.setText(String.valueOf(product.price));
            
            shoesQty = product.getQuantity();
            
            while(shoesQty>product.stock){
                shoesQty = Integer.parseInt(JOptionPane.showInputDialog("Over stock limit. Enter new amount: "));
            }
            
            shoesStock.setText(String.valueOf(product.stockRemain(shoesQty)));
            
            netTotal+=product.calcPrice(shoesQty);
            
            NETTOTAL.setText(String.valueOf(df.format(netTotal)));
            shoesQtyInCart.setText(String.valueOf(shoesQty));
        }
        
        if (!shoesButton.isSelected()){
            shoesStock.setText(String.valueOf(product.stock));
            shoesPrice.setText(String.valueOf(product.price));
            shoesQtyInCart.setText("0");
            
            revertPrice(product.calcPrice(shoesQty));
        }
    }//GEN-LAST:event_shoesButtonActionPerformed

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Your total is: " + df.format(netTotal));
    }//GEN-LAST:event_buyButtonActionPerformed

    private void revertPrice(double a){
        netTotal-=a;
        NETTOTAL.setText(String.valueOf(df.format(netTotal)));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NETTOTAL;
    private javax.swing.JRadioButton bagButton;
    private javax.swing.JTextField bagPrice;
    private javax.swing.JTextField bagQtyInCart;
    private javax.swing.JTextField bagStock;
    private javax.swing.JToggleButton buyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton shirtButton;
    private javax.swing.JTextField shirtPrice;
    private javax.swing.JTextField shirtQtyInCart;
    private javax.swing.JTextField shirtStock;
    private javax.swing.JRadioButton shoesButton;
    private javax.swing.JTextField shoesPrice;
    private javax.swing.JTextField shoesQtyInCart;
    private javax.swing.JTextField shoesStock;
    private javax.swing.JRadioButton trousersButton;
    private javax.swing.JTextField trousersPrice;
    private javax.swing.JTextField trousersQtyInCart;
    private javax.swing.JTextField trousersStock;
    // End of variables declaration//GEN-END:variables
}
